export const httpCodes = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};

export const DefaultDepartments = {
  MEDECINE_GENERAL: "Medecine General",
  SOINS_INFIRMIERS: "Soins Infirmiers",
  CHIRURGIE: "Chirurgie",
  PEDIATRIE: "Pediatrie",
  MEDECINE_INTERNE: "Medecine Interne",
  PETITE_CHIRURGIE: "Petite Chirurgie",
  LABORATOIRE: "Laboratoire",
  GYNECO_OBSTETRIQUE: "Gyneco-obstetrique",
  RADIOLOGIE: "Radiologie",
  KINESITHERAPIE: "Kinesitherapie",
  ORL: "O.R.L",
  PLATRE_ORDINAIRE: "Platre Ordinare",
  DERMATOLOGIE: "Dermatologie",
  REDUCTION_FRACTURES: "Reduction Fractures",
  STOMATOLOGIE: "Stomatologie",
  OPHTALMOLOGIE: "Ophthalmologie",
  EXAMENS_SPECIAUX: "Examens Speciaux",
  ANESTHESIE: "Anesthesie",
  AUTRES_PROCEDURES: "Autres Procedures",
};

export const Consultations = {
  SUIVI_UN_ANCIEN_CAS: "SUIVI (UN ANCIEN CAS)",
  CONSULTATION_PAR_UN_GENERALISTE_CHIRURGIEN_DENTISTE:
    "CONSULTATION PAR UN GENERALISTE, CHIRURGIEN DENTISTE",
  CONSULTATION_PAR_UN_SPECIALISTE: "CONSULTATION PAR UN SPECIALISTE",
  SUIVI_D_UN_MALADE_HOSPITALISE: "SUIVI D'UN MALADE HOSPITALISE",
  CONSULTATIONS_DES_PARAMEDICAUX_A0_KINESITHERAPEUTE_TECHNlCIEN_DENTAIRE_OPHTALMOLOGISTE_SANTE_MENTALE_NUTRITIONNISTE:
    "CONSULTATIONS DES PARAMEDICAUX A0: KINESITHERAPEUTE, TECHNlCIEN DENTAIRE, OPHTALMOLOGISTE, SANTE MENTALE, NUTRITIONNISTE",
  CONSULTATIONS_DES_PARAMEDICAUX_A1_KINESITHERAPEUTE_TECHNlCIEN_DENTAIRE_OPHTALMOLOGISTE_SANTE_MENTALE_NUTRITIONNISTE:
    "CONSULTATIONS DES PARAMEDICAUX A1: KINESITHERAPEUTE, TECHNlCIEN DENTAIRE, OPHTALMOLOGISTE, SANTE MENTALE, NUTRITIONNISTE",
  CONSULTATION_PAR_INFIRMIER_A1_DANS_UN_DISPENSAIRE:
    "CONSULTATION PAR INFIRMIER A1 DANS UN DISPENSAIRE",
  CONSULTATION_PAR_INFIRMIER_A2_DANS_UN_DISPENSAIRE:
    "CONSULTATION PAR INFIRMIER A2 DANS UN DISPENSAIRE",
  CONSULTATION_WEEK_END_JOURS_FERIES_ET_NUITS_PAR_GENERALISTE_ET_CHIURGIEN_DENTISTE:
    "CONSULTATION WEEK END, JOURS FERIES ET NUITS PAR GENERALISTE ET CHIURGIEN DENTISTE",
  CONSULTATION_WEEK_END_JOURS_FERIES_ET_NUITS_PAR_SPECIALISTE:
    "CONSULTATION WEEK END, JOURS FERIES ET NUITS PAR SPECIALISTE",
};
